# Generated by Django 2.0.2 on 2018-03-21 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='keychain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('network', models.CharField(default='not assigned', max_length=50)),
                ('public_key_x', models.CharField(default='not assigned', max_length=300)),
                ('public_key_y', models.CharField(default='not assigned', max_length=300)),
                ('private_key', models.CharField(default='not assigned', max_length=300)),
                ('sec', models.CharField(default='not assigned', max_length=300)),
                ('coinAddress', models.CharField(default='not assigned', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='KYCdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar', models.ImageField(blank=True, upload_to='media/aadhaar/')),
                ('PAN', models.ImageField(blank=True, upload_to='media/pan/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_KYCverified', models.BooleanField(default=False)),
                ('key_generated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'KYCdata',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
